// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-categories.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}

// src/lib/mcp/tools/list-categories.ts
var list_categories_default = defineTool({
  name: "list_categories",
  title: "List categories",
  description: "List all Musabaqa competition categories with their max scores.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("categories").select("id, name, description, max_memorization, max_tajweed, max_voice, max_dressing").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-participants.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_participants_default = defineTool2({
  name: "list_participants",
  title: "List participants",
  description: "List participants, optionally filtered by category id.",
  inputSchema: {
    category_id: z.string().uuid().optional().describe("Optional category id filter")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ category_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let q = sb.from("participants").select("id, full_name, date_of_birth, category_id, categories(name)");
    if (category_id) q = q.eq("category_id", category_id);
    const { data, error } = await q.order("full_name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { participants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-results.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_results_default = defineTool3({
  name: "get_results",
  title: "Get results and rankings",
  description: "Compute average total scores per participant, optionally filtered by category, ranked highest first.",
  inputSchema: {
    category_id: z2.string().uuid().optional().describe("Optional category id filter")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ category_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let pq = sb.from("participants").select("id, full_name, category_id, categories(name)");
    if (category_id) pq = pq.eq("category_id", category_id);
    const { data: participants, error: pErr } = await pq;
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    const ids = (participants ?? []).map((p) => p.id);
    if (ids.length === 0) {
      return { content: [{ type: "text", text: "[]" }], structuredContent: { results: [] } };
    }
    const { data: scores, error: sErr } = await sb.from("scores").select("participant_id, total_score").in("participant_id", ids);
    if (sErr) return { content: [{ type: "text", text: sErr.message }], isError: true };
    const map = /* @__PURE__ */ new Map();
    for (const s of scores ?? []) {
      const cur = map.get(s.participant_id) ?? { sum: 0, count: 0 };
      cur.sum += Number(s.total_score) || 0;
      cur.count += 1;
      map.set(s.participant_id, cur);
    }
    const results = (participants ?? []).map((p) => {
      const agg = map.get(p.id);
      const average = agg && agg.count ? agg.sum / agg.count : 0;
      return {
        participant_id: p.id,
        full_name: p.full_name,
        category: p.categories?.name ?? null,
        judges_scored: agg?.count ?? 0,
        average_score: Number(average.toFixed(2))
      };
    }).sort((a, b) => b.average_score - a.average_score).map((r, i) => ({ rank: i + 1, ...r }));
    return {
      content: [{ type: "text", text: JSON.stringify(results) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/list-my-scores.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_my_scores_default = defineTool4({
  name: "list_my_scores",
  title: "List my submitted scores",
  description: "List all scores submitted by the currently signed-in judge.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("scores").select("id, participant_id, memorization_score, memorization_mistakes, tajweed_score, voice_score, dressing_score, total_score, updated_at, participants(full_name)").eq("judge_id", ctx.getUserId()).order("updated_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { scores: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-score.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var submit_score_default = defineTool5({
  name: "submit_score",
  title: "Submit a score",
  description: "Submit or update the signed-in judge's score for a participant. total_score = memorization + tajweed + voice + dressing.",
  inputSchema: {
    participant_id: z3.string().uuid(),
    memorization_score: z3.number().min(0),
    memorization_mistakes: z3.number().int().min(0).default(0),
    tajweed_score: z3.number().min(0),
    voice_score: z3.number().min(0),
    dressing_score: z3.number().min(0)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const total = input.memorization_score + input.tajweed_score + input.voice_score + input.dressing_score;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("scores").upsert(
      {
        judge_id: ctx.getUserId(),
        participant_id: input.participant_id,
        memorization_score: input.memorization_score,
        memorization_mistakes: input.memorization_mistakes,
        tajweed_score: input.tajweed_score,
        voice_score: input.voice_score,
        dressing_score: input.dressing_score,
        total_score: total
      },
      { onConflict: "judge_id,participant_id" }
    ).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { score: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eouuztdfdsiubhzaxdjj";
var mcp_default = defineMcp({
  name: "musabaqa-mcp",
  title: "Musabaqa MCP",
  version: "0.1.0",
  instructions: "Tools for the Musabaqa Qur'anic competition management system. Use `list_categories` and `list_participants` to browse, `get_results` for rankings, and (for judges) `list_my_scores` and `submit_score` to review and enter scores.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_categories_default, list_participants_default, get_results_default, list_my_scores_default, submit_score_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
